export const ROUTES = {
  login: "/login",
  forbidden: "/403",
  dashboard: "/dashboard",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminAssignments: "/admin/assignments",
  patient: "/patient",
  patientRequest: "/patient/request",
  patientSchedule: "/patient/schedule",
  patientProfile: "/patient/profile",
  caregiver: "/caregiver",
  caregiverRequests: "/caregiver/requests",
  caregiverSchedule: "/caregiver/schedule",
  caregiverProfile: "/caregiver/profile",
  register: "/register",
  registerDetails: "/register/details",
  apiAuthSession: "/api/auth/session",
} as const;
